import { defineTable } from 'convex/server'
import { v } from 'convex/values'
const scope = { businessId: v.string(), email: v.string() }
export const emailTables = {
  emailCampaigns: defineTable({
    businessId: v.string(),
    revision: v.optional(v.number()),
    planRevision: v.optional(v.number()),
    dispatchEpoch: v.optional(v.number()),
    firstLotComplete: v.optional(v.boolean()),
    counters: v.optional(v.any()),
    expansionComplete: v.optional(v.boolean()),
    reviewCutoff: v.optional(v.number()),
    state: v.string(),
    versionId: v.optional(v.id('emailCampaignVersions')),
    approvedVersionId: v.optional(v.id('emailCampaignVersions')),
    approvedRoute: v.optional(v.string()),
    approvedScheduledAt: v.optional(v.number()),
    resumeState: v.optional(v.string()),
    pausedAt: v.optional(v.number()),
    blockReason: v.optional(v.string()),
    operationId: v.optional(v.id('emailCampaignRequests')),
    snapshotCursor: v.optional(v.string()),
    snapshotComplete: v.optional(v.boolean()),
    scanned: v.optional(v.number()),
    eligible: v.optional(v.number()),
    excluded: v.optional(v.number()),
    fanoutCursor: v.optional(v.string()),
    fanoutQueued: v.optional(v.number()),
    fanoutExcluded: v.optional(v.number()),
    nextAt: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index('business', ['businessId'])
    .index('due', ['businessId', 'state', 'nextAt']),
  emailCampaignVersions: defineTable({
    businessId: v.string(),
    campaignId: v.id('emailCampaigns'),
    number: v.number(),
    audienceId: v.string(),
    purpose: v.string(),
    locale: v.string(),
    subject: v.string(),
    title: v.optional(v.string()),
    preheader: v.optional(v.string()),
    blocks: v.optional(v.any()),
    paragraphs: v.array(v.string()),
    scheduledAt: v.number(),
    timezone: v.string(),
    rendered: v.any(),
    cutoff: v.number(),
    route: v.string(),
    createdAt: v.number(),
  }).index('campaign', ['campaignId', 'number']),
  emailCampaignRecipients: defineTable({
    businessId: v.string(),
    campaignId: v.id('emailCampaigns'),
    versionId: v.id('emailCampaignVersions'),
    membershipId: v.id('emailMemberships'),
    generation: v.number(),
    canonicalContactKey: v.optional(v.string()),
    ledgerId: v.optional(v.id('emailCampaignRecipientLedger')),
    state: v.string(),
    messageId: v.optional(v.id('emailMessages')),
    reason: v.optional(v.string()),
  })
    .index('member', ['versionId', 'membershipId'])
    .index('version', ['versionId'])
    .index('campaign', ['campaignId']),
  // This ledger deliberately outlives a content version and a remaining-plan
  // revision. It is the durable boundary that prevents a resend by alias,
  // revision, retry, or worker restart.
  emailCampaignRecipientLedger: defineTable({
    businessId: v.string(),
    campaignId: v.id('emailCampaigns'),
    canonicalContactKey: v.string(),
    state: v.string(),
    planRevision: v.number(),
    reservationAttemptId: v.optional(v.id('emailAttempts')),
    departureAuthorizedAt: v.optional(v.number()),
    updatedAt: v.number(),
  })
    .index('campaign_contact', ['campaignId', 'canonicalContactKey'])
    .index('campaign', ['campaignId']),
  emailCampaignRequests: defineTable({
    businessId: v.string(),
    clientId: v.string(),
    key: v.string(),
    fingerprint: v.string(),
    result: v.any(),
    at: v.number(),
  }).index('scope', ['businessId', 'clientId', 'key']),
  emailCampaignPolicies: defineTable({
    businessId: v.string(),
    identityKey: v.string(),
    revision: v.number(),
    status: v.string(),
    evidenceMaxAge: v.any(),
    executionLimits: v.optional(v.any()),
    approvedAt: v.number(),
  }).index('scope', ['businessId', 'identityKey', 'revision']),
  emailCampaignEvidence: defineTable({
    businessId: v.string(),
    campaignId: v.id('emailCampaigns'),
    versionId: v.id('emailCampaignVersions'),
    kind: v.string(),
    source: v.string(),
    owner: v.string(),
    scopeDigest: v.string(),
    collectedAt: v.number(),
    validUntil: v.number(),
    sourceRevision: v.string(),
    status: v.string(),
    reason: v.optional(v.string()),
    evidenceRef: v.string(),
  }).index('campaign', ['campaignId', 'versionId', 'kind']),
  emailCampaignReports: defineTable({
    businessId: v.string(),
    campaignId: v.id('emailCampaigns'),
    versionId: v.id('emailCampaignVersions'),
    revision: v.number(),
    scopeDigest: v.string(),
    policyRevision: v.number(),
    checkedAt: v.number(),
    expiresAt: v.number(),
    status: v.string(),
    blockingChecks: v.array(v.any()),
    warningChecks: v.array(v.any()),
    evidenceIds: v.array(v.string()),
  }).index('campaign', ['campaignId', 'revision']),
  emailOperatorChallenges: defineTable({
    challengeId: v.string(),
    actorId: v.string(),
    sessionRef: v.string(),
    businessId: v.string(),
    action: v.string(),
    scopeDigest: v.string(),
    reportId: v.optional(v.id('emailCampaignReports')),
    revision: v.optional(v.number()),
    expiresAt: v.number(),
    usedAt: v.optional(v.number()),
  }).index('challenge', ['challengeId']),
  emailAddresses: defineTable({
    email: v.string(),
    globalUserId: v.optional(v.id('globalUsers')),
    createdAt: v.number(),
  }).index('email', ['email']),
  emailAudiences: defineTable({
    businessId: v.string(),
    audienceId: v.string(),
    purpose: v.string(),
  }).index('scope', ['businessId', 'audienceId']),
  emailConsents: defineTable({
    ...scope,
    audienceId: v.string(),
    purpose: v.string(),
    action: v.string(),
    source: v.string(),
    noticeVersion: v.string(),
    locale: v.string(),
    occurredAt: v.optional(v.number()),
    at: v.number(),
  }).index('scope', ['businessId', 'email']),
  emailMemberships: defineTable({
    ...scope,
    audienceId: v.string(),
    purpose: v.string(),
    state: v.string(),
    generation: v.number(),
    updatedAt: v.number(),
  })
    .index('scope', ['businessId', 'email', 'audienceId'])
    .index('email', ['email'])
    .index('audience', ['businessId', 'audienceId']),
  emailSuppressions: defineTable({
    ...scope,
    email: v.optional(v.string()),
    emailDigest: v.optional(v.string()),
    streamId: v.optional(v.string()),
    reason: v.string(),
    at: v.number(),
  })
    .index('scope', ['businessId', 'email'])
    .index('digest', ['businessId', 'emailDigest']),
  emailRequests: defineTable({
    businessId: v.string(),
    clientId: v.string(),
    key: v.string(),
    fingerprint: v.string(),
    email: v.optional(v.string()),
    result: v.any(),
    at: v.number(),
  })
    .index('scope', ['businessId', 'clientId', 'key'])
    .index('contact', ['businessId', 'email']),
  emailTokens: defineTable({
    ...scope,
    audienceId: v.string(),
    purpose: v.string(),
    source: v.optional(v.string()),
    noticeVersion: v.optional(v.string()),
    locale: v.optional(v.string()),
    digest: v.string(),
    kind: v.string(),
    generation: v.number(),
    expiresAt: v.number(),
    usedAt: v.optional(v.number()),
  })
    .index('digest', ['digest'])
    .index('scope', ['businessId', 'email']),
  emailMessages: defineTable({
    ...scope,
    audienceId: v.optional(v.string()),
    purpose: v.optional(v.string()),
    kind: v.string(),
    campaignId: v.optional(v.id('emailCampaigns')),
    campaignVersionId: v.optional(v.id('emailCampaignVersions')),
    campaignRecipientId: v.optional(v.id('emailCampaignRecipients')),
    campaignLedgerId: v.optional(v.id('emailCampaignRecipientLedger')),
    campaignMembershipGeneration: v.optional(v.number()),
    rendered: v.any(),
    state: v.string(),
    createdAt: v.number(),
    nextAt: v.number(),
    leaseUntil: v.optional(v.number()),
    providerMessageId: v.optional(v.string()),
    route: v.optional(v.string()),
  })
    .index('queue', ['businessId', 'state', 'nextAt'])
    .index('queue_kind', ['businessId', 'state', 'kind', 'nextAt'])
    .index('provider', ['providerMessageId'])
    .index('contact', ['businessId', 'email']),
  emailAttempts: defineTable({
    businessId: v.string(),
    messageId: v.id('emailMessages'),
    state: v.string(),
    at: v.number(),
    errorCode: v.optional(v.string()),
    route: v.optional(v.string()),
    dispatchReservedAt: v.optional(v.number()),
    campaignId: v.optional(v.id('emailCampaigns')),
    campaignLedgerId: v.optional(v.id('emailCampaignRecipientLedger')),
    canonicalContactKey: v.optional(v.string()),
    identityKey: v.optional(v.string()),
    dispatchEpoch: v.optional(v.number()),
    reservedAt: v.optional(v.number()),
    authorizedAt: v.optional(v.number()),
    releasedAt: v.optional(v.number()),
    releaseProof: v.optional(v.string()),
  }).index('message', ['messageId']),
  emailEvents: defineTable({
    businessId: v.string(),
    eventId: v.string(),
    type: v.string(),
    messageId: v.optional(v.id('emailMessages')),
    providerMessageId: v.optional(v.string()),
    occurredAt: v.optional(v.number()),
    at: v.number(),
  })
    .index('scope', ['businessId', 'eventId'])
    .index('message', ['businessId', 'messageId']),
  emailTestQuotas: defineTable({
    businessId: v.string(),
    profileId: v.string(),
    maxAttempts: v.number(),
    attempts: v.number(),
  }).index('scope', ['businessId', 'profileId']),
  emailRateLimits: defineTable({
    businessId: v.string(),
    key: v.string(),
    window: v.number(),
    count: v.number(),
  }).index('scope', ['businessId', 'key', 'window']),
}
